version: '3'
services:
  munchkin-server:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["node", "dist/server.js"]
